// frontend/src/components/MeComponent.tsx
import { useQuery } from "@tanstack/react-query"
import { GetMe } from "../lib/auth"

export function MeComponent() {
	const { isPending, error, data } = useQuery({
		queryKey: ["getMe"],
		queryFn: GetMe
	})

	if (isPending) {
		return (<h1>Pending Me ...</h1>)
	}

	if (error) {
		return (<h1>error Me ${error.message}</h1>)
	}
	return <h1>user id:{data.id}</h1>
}

// frontend/src/components/MeComponent.vue
<script setup lang="ts">
import { AccountService } from '@/gen/account/v1/account_pb';
import { authTransport } from '@/lib/transport';
import { createClient } from "@connectrpc/connect";
import { useQuery } from '@tanstack/vue-query';

const { isPending, error, data } = useQuery({
  queryKey: ['me'],
  queryFn: async () => {
    const client = createClient(AccountService, authTransport)
    const data = await client.getMe({})
    return data
  }
})
</script>


<template>
  <span v-if="isPending">Loading...</span>
  <span v-else-if="error">{{ error.message }}</span>
  <h1 v-else>user id:{{ data?.account?.id }}</h1>
</template>
