// frontend/src/components/chat/ChatBubble.vue
<script setup lang="ts">

import profilePic from '@/assets/profile.jpg'

const props = defineProps({
  isMe: { required: true, type: Object as () => boolean },
  text: { required: true, type: Object as () => string }
})

</script>

<template>

  <div :class="['flex items-end gap-2.5', props.isMe ? 'flex-row-reverse' : '']">
    <img :src="profilePic" class='w-10 h-10 rounded-full' alt="profile image" />
    <div :class="['max-w-1/2 rounded-t-xl p-3 break-words', props.isMe ? 'bg-emerald-100 rounded-l-xl'
      : 'bg-gray-100 rounded-r-xl']">
      <p dir="auto">{{ props.text }}</p>
    </div>
  </div>
</template>

// frontend/src/components/Chat/ChatBubble.tsx
import { detectDirection } from '../../lib/lang'
import profilePic from '../../assets/profile.jpg'

type ChatBubbleProps = {
	message: string
	isMe: boolean
}

export function ChatBubble({ message, isMe }: ChatBubbleProps) {
	return (
		<>
			<div className={`flex ${isMe ? "flex-row-reverse" : ""} items-end gap-2.5`} >
				<img src={profilePic}
					className='w-10 h-10 rounded-full' alt="profile image"
				/>
				<div className={`max-w-1/2 rounded-t-xl p-3 break-words
					${isMe ? "rounded-l-xl" : "rounded-r-xl"}
					${isMe ? "bg-emerald-100" : "bg-gray-100"}
					`}>
					<p dir={detectDirection(message)}>{message}</p>
				</div >
			</div >
		</>
	)
}
