// frontend/src/components/Chat/Chat.tsx
import { useEffect, useRef, useState } from "react";
import { SessionSocket } from "../../lib/SessionWs";
import { fetchWithAuth, GetMe } from "../../lib/auth";
import { useQuery } from "@tanstack/react-query";
import { ChatBubble } from "./ChatBubble";
import { ChatInput } from "./ChatInput";
import { GetBaseUrl } from "../../lib/baseURL";
import { Message } from "../../types/Message";

type ChatProps = {
	socketRef: React.RefObject<SessionSocket>
};

export function Chat({ socketRef }: ChatProps) {
	const chatRef = useRef<HTMLDivElement>(null);
	const [showMessages, setShowMessages] = useState(false);
	const [messages, setMessages] = useState<Message[]>([]);

	// Get current user
	const { isPending, error, data: me } = useQuery({
		queryKey: ["getMe"],
		queryFn: GetMe
	});

	// Fetch chat history once on mount
	useEffect(() => {
		GetChatHistory()
			.then(history => {
				setMessages(history.messages.map(m => new Message(m.text, m.sender_id)));
			})
			.catch(err => {
				console.error("Failed to load chat history:", err);
			});
	}, []);

	// Handle click outside chat to hide
	const handleClick = (event: MouseEvent) => {
		if (chatRef.current && chatRef.current.contains(event.target as Node)) {
			setShowMessages(false);
		}
	};
	useEffect(() => {
		document.addEventListener("mousedown", handleClick);
		return () => document.removeEventListener("mousedown", handleClick);
	}, []);

	// Auto scroll when new messages appear
	useEffect(() => {
		if (showMessages && chatRef.current) {
			chatRef.current.scrollTop = chatRef.current.scrollHeight;
		}
	}, [messages, showMessages]);

	if (isPending) return <h1>Pending Me ...</h1>;
	if (error) return <h1>error Me {String(error)}</h1>;

	// Receive new message from socket
	socketRef.current.HandleChatMessage = (chatMessage) => {
		setMessages(prev => [...prev, new Message(chatMessage.text, chatMessage.playerId)]);
	};


	// Send message
	const sendMessage = (message: string) => {
		setMessages(prev => [...prev, new Message(message, me.id)]);
		socketRef.current.SendChatMessage(message);
	};

	return (
		<div className="absolute bottom-0" >
			{showMessages &&
				< div className="flex flex-col w-full h-full justify-end font-[Rubik]">
					<div className="flex flex-col w-full h-full overflow-hidden">
						<div
							className={`flex flex-col gap-3 px-4 py-2 overflow-y-auto flex-grow transition-all duration-1000
						${showMessages ? "opacity-100 bg-gray-800/50" : "opacity-0 "}`}
							ref={chatRef}
						>
							{messages.map((msg, index) => (
								<ChatBubble key={index} message={msg.text} isMe={msg.userID === me.id} />
							))}
						</div>
					</div>
				</div>
			}
			<ChatInput setShowMessage={setShowMessages} sendMessage={sendMessage} />
		</div >
	);
}

interface MessageResponse {
	id: number;
	text: string;
	sender_id: number;
}

interface ChatHistoryResponse {
	messages: Array<MessageResponse>;
}

export async function GetChatHistory() {
	const response = await fetchWithAuth(GetBaseUrl() + "/api/session/chat/history");
	if (response.status !== 200) {
		throw new Error(response.statusText);
	}
	const json_data: ChatHistoryResponse = await response.json();
	return json_data;
}

// frontend/src/components/chat/Chat.vue
<script setup lang="ts">
import ChatInput from '@/components/chat/ChatInput.vue';
import { SessionService, type ChatMessage } from '@/gen/session/v1/session_pb';
import type { SessionSocket } from '@/lib/SessionWs';
import { Message } from '@/types/Message';
import { useTemplateRef, watch } from 'vue';
import { onMounted, onUnmounted, ref } from 'vue';
import ChatBubble from './ChatBubble.vue';


import { authTransport } from '@/lib/transport';
import { AccountService } from '@/gen/account/v1/account_pb';
import { createClient } from '@connectrpc/connect'
import { useQuery } from '@tanstack/vue-query';

const { isPending: meIsPending, error: meErr, data: meData } = useQuery({
  queryKey: ['me'],
  queryFn: async () => {
    const client = createClient(AccountService, authTransport)
    const data = await client.getMe({})
    return data
  }
})

const { isPending: chatHistoryIsPending, error: chatHistoryErr, data: chatHistoryData } = useQuery({
  queryKey: ['chat-history'],
  queryFn: async () => {
    const client = createClient(SessionService, authTransport)
    const data = await client.getChatHistory({})
    return data
  },
  staleTime: 0
})

watch(chatHistoryData, () => {
  if (chatHistoryData && chatHistoryData.value) {
    const oldMessages = chatHistoryData.value.messages.map(
      (m) => new Message(m.text, m.playerId)
    )
    allChatMessages.value = oldMessages
  }
})

const allChatMessages = ref(Array<Message>())
const showChat = ref(false)

const chatInput = useTemplateRef('chat-input')

watch(showChat, () => {
  console.log("show " + showChat)
})

const props = defineProps({
  sessionSocket: {
    type: Object as () => SessionSocket,
    required: true,
  }
})

function sendMessage(msgText: string) {
  if (msgText == "") {
    return
  }
  props.sessionSocket.SendChatReqMessage(msgText)
  if (meData) {
    allChatMessages.value.push(new Message(msgText, meData.value!.account!.id))
  }
}

function HandleIncomingChat(chatMsg: ChatMessage) {
  allChatMessages.value.push(new Message(chatMsg.text, chatMsg.playerId))
}

function handleOutClick(event: MouseEvent) {
  if (chatInput.value && !chatInput.value.contains(event.target as Node)) {
    showChat.value = false
  }
}

onMounted(() => {
  document.addEventListener("mousedown", handleOutClick);
})
onUnmounted(() => {
  document.removeEventListener("mousedown", handleOutClick);
})

defineExpose({
  HandleIncomingChat
})
</script>

<template>
  <div v-if="meData" class="absolute bottom-0">

    <div class="flex flex-col w-full h-full justify-end font-[Rubik]">
      <div class="flex flex-col w-full h-full overflow-hidden">
        <div :class="[`flex flex-col gap-3 px-4 py-2 overflow-y-auto flex-grow transition-all duration-1000`,
          showChat ? 'opacity-100 bg-gray-800/50' : 'opacity-0']">
          <ChatBubble v-for="msg in allChatMessages" :text="msg.text" :is-me="meData!.account?.id ==
            msg.userID" />
        </div>
      </div>
    </div>
    <div ref="chat-input">
      <ChatInput @input-click="showChat = true" @submit="sendMessage" />
    </div>
  </div>
</template>
